name: mobile_meumoney
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.2.0 #Internacionalização
  mobx: ^2.0.0
  dio: ^4.0.0
  flutter_mobx: ^2.0.0
  flutter_modular: ^3.2.0
  dartz: ^0.10.0-nullsafety.1
  flutter_svg: ^0.22.0
  rounded_loading_button: ^2.0.3
  asuka: ^2.0.0-nullsafety.2
  eva_icons_flutter: ^3.0.0
  animated_bottom_navigation_bar: ^0.3.2
  flutter_triple: ^1.0.6

dev_dependencies:
  mobx_codegen: ^2.0.1+3
  modular_codegen: ^3.0.0
  build_runner: ^2.0.2
  mockito: ^5.0.7
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/app/shared/assets/images/logo.svg
  fonts:
     - family: PoppinsBlack
       fonts:
        - asset: lib/app/shared/assets/fonts/Poppins-Black.ttf

     - family: PoppinsBold
       fonts:
        - asset: lib/app/shared/assets/fonts/Poppins-Bold.ttf

     - family: PoppinsLight
       fonts:
        - asset: lib/app/shared/assets/fonts/Poppins-Light.ttf

     - family: PoppinsMedium
       fonts:
        - asset: lib/app/shared/assets/fonts/Poppins-Medium.ttf

     - family: PoppinsRegular
       fonts:
        - asset: lib/app/shared/assets/fonts/Poppins-Regular.ttf

     - family: PoppinsSemiBold
       fonts:
        - asset: lib/app/shared/assets/fonts/Poppins-SemiBold.ttf
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: LocaleProvider
  main_locale: pt_BR
  arb_dir: lib/app/shared/translation/l10n
  output_dir: lib/app/shared/translation/generated

scripts:
  mobx: flutter clean & flutter pub get & flutter pub run build_runner watch --delete-conflicting-outputs
